const assert = require('node:assert/strict');
const fs = require('node:fs'), path = require('node:path'), http = require('node:http');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = path.resolve(process.env.TEST_ROOT || path.join(__dirname,'../..'));
const overlay = process.env.TEST_OVERLAY && path.resolve(process.env.TEST_OVERLAY);
const output = path.resolve(process.env.TEST_OUTPUT || path.join(__dirname,'artifacts/collections'));
fs.mkdirSync(output,{recursive:true});
const server = http.createServer((req,res) => {
  const pathname = decodeURIComponent(new URL(req.url,'http://localhost').pathname);
  let file = path.resolve(root,'.'+pathname);
  if (!file.startsWith(root+path.sep)) {res.writeHead(403);return res.end();}
  if (overlay && pathname.startsWith('/v2/')) {const candidate = path.resolve(overlay,'.'+pathname);if(fs.existsSync(candidate))file=candidate;}
  if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');
  fs.readFile(file,(error,data)=>{res.writeHead(error?404:200,{'Content-Type':{'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css','.png':'image/png','.svg':'image/svg+xml'}[path.extname(file)]||'application/octet-stream'});res.end(error?'Not found':data);});
});
const fixture = balance => ({pseudo:'Explorateur Nocturne',stats:{totalCJ:balance,byGame:{attrape:10},playTime:{totalSeconds:600,byGame:{attrape:600}}},items:{unlockedBadges:{},unlockedCosmetics:{}},unlockedImages:{},custom:{keep:true}});
let browser;const checks=[],errors=[];
(async()=>{
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
browser=await chromium.launch({headless:true,channel:'msedge'});const context=await browser.newContext();const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/v2/#boutique');
assert.equal(await page.evaluate(()=>localStorage.length),0);
const set=async balance=>{await page.evaluate(p=>{localStorage.setItem('cjPlayerData',JSON.stringify(p));localStorage.setItem('game-save','unchanged');},fixture(balance));await page.reload();};
const read=()=>page.evaluate(()=>CJajlkAccount.getPlayer());const buy=id=>page.evaluate(id=>CJShop.buy(id),id);const card=id=>page.locator(`[data-shop-item="${id}"]`);
await set(100);await page.evaluate(()=>{window.commits=0;window.debits=0;const save=CJajlkAccount.savePlayer,spend=CJajlkAccount.spendCJ;CJajlkAccount.savePlayer=function(p){commits++;return save.call(this,p)};CJajlkAccount.spendCJ=function(n){debits++;return spend.call(this,n)}});
await card('breaker_mascotte_1').locator('button').dblclick();await page.waitForTimeout(800);assert.equal((await read()).stats.totalCJ,80);assert.equal(await page.evaluate(()=>commits),1);assert.equal(await page.evaluate(()=>debits),1);assert.equal((await read()).profileV2,undefined);
await card('breaker_mascotte_1').locator('button').click();await page.waitForTimeout(700);assert.equal((await read()).profileV2.avatar,'breaker_mascotte_1');await card('breaker_mascotte_1').locator('button').click();await page.waitForTimeout(700);assert.equal((await read()).profileV2.avatar,null);assert((await read()).unlockedImages.breaker_mascotte_1);assert.equal((await buy('breaker_mascotte_1')).code,'owned');await page.reload();assert((await read()).unlockedImages.breaker_mascotte_1);checks.push('Avatar UI, double clic : un débit de 20 CJ et une écriture ; équipement, déséquipement, possession permanente et reload.');
await page.locator('[data-shop-category=badge]').click();await card('explorer').locator('button').click();await page.waitForTimeout(700);assert.equal((await read()).stats.totalCJ,70);await card('explorer').locator('button').click();await page.waitForTimeout(700);assert.equal((await read()).selectedBadge,'explorer');assert.equal(await page.locator('.shop-item').count(),4);assert.equal((await buy('paques')).code,'unavailable');checks.push('Badge : débit de 10 CJ, équipement ; quatre badges visibles, Pâques hors événement non achetable.');
await set(0);assert.equal((await buy('explorer')).code,'funds');assert.equal((await read()).stats.totalCJ,0);
await set(100);await page.evaluate(()=>{CJajlkAccount.savePlayer=()=>{}});assert.equal((await buy('explorer')).code,'storage');assert.equal((await read()).stats.totalCJ,100);assert.deepEqual((await read()).items.unlockedBadges,{});await page.reload();await page.evaluate(()=>{Storage.prototype.setItem=()=>{throw new DOMException('Full','QuotaExceededError')}});assert.equal((await buy('explorer')).code,'storage');assert.equal((await read()).stats.totalCJ,100);await page.reload();checks.push('Solde insuffisant et sauvegarde silencieusement refusée / quota : aucun débit ni objet attribué.');
const second=await context.newPage();await second.goto(base+'/v2/#boutique');const results=await Promise.all([buy('explorer'),second.evaluate(()=>CJShop.buy('explorer'))]);assert.equal(results.filter(r=>r.code==='purchased').length,1);assert.equal(results.filter(r=>r.code==='owned').length,1);assert.equal((await read()).stats.totalCJ,90);assert.equal(await second.locator('#shop-balance').textContent(),'90');await second.close();checks.push('Deux onglets concurrents : un seul achat, un seul débit, solde synchronisé.');
for(let i=0;i<4;i++)assert((await page.evaluate(i=>CJCollections.buy('plage_volley',i),i)).ok);assert.equal((await read()).stats.totalCJ,82);await page.locator('[data-shop-category=background]').click();await card('collection_plage_volley').locator('button').click();await page.waitForTimeout(700);assert.equal((await read()).profileV2.background,'collection_plage_volley');await card('collection_plage_volley').locator('button').click();await page.waitForTimeout(700);assert((await read()).items.unlockedCosmetics.collection_plage_volley);await page.locator('[data-shop-category=collections]').click();assert.match(await page.locator('#shop-grid').textContent(),/4\/12 morceaux acquis/);assert.deepEqual((await read()).stats.playTime,fixture(100).stats.playTime);assert.deepEqual((await read()).stats.byGame,fixture(100).stats.byGame);assert.equal(await page.evaluate(()=>localStorage.getItem('game-save')),'unchanged');checks.push('Collection 4/4 coûte toujours 8 CJ ; fond présent, équipable et conservé ; temps et sauvegarde jeu inchangés.');
await page.locator('[data-shop-category=avatar]').click();
for(const width of [320,390,760,768,1024,1440]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));for(const b of await page.locator('.shop-item button').all())assert((await b.boundingBox()).height>=48);for(const img of await page.locator('.shop-preview img').all())assert(await img.evaluate(i=>i.complete&&i.naturalWidth>0));if([390,1440].includes(width)){await page.evaluate(()=>{document.getElementById('main').focus({preventScroll:true});scrollTo(0,0)});await page.screenshot({path:path.join(output,`shop-${width}.png`),fullPage:true});}}
await page.locator('[data-shop-category=badge]').click();await page.screenshot({path:path.join(output,'shop-badges-1440.png'),fullPage:true});assert.deepEqual(errors,[]);checks.push('Six largeurs desktop/mobile sans débordement, boutons ≥48px, images chargées, aucune erreur JavaScript.');fs.writeFileSync(path.join(output,'shop-tests.json'),JSON.stringify({passed:true,checks,errors},null,2));console.log(JSON.stringify({passed:true,checks},null,2));
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();server.close()});